baseURL = "https://jtndvs.com"
title = "Jonathan Davies"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "UA-221022733-1"

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "ExampleSite"
description = "ExampleSite description"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Jonathan"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = true

  [params.assets]
  favicon = "/favicon.ico"
  favicon16x16 = "/favicon16x16.png"
  favicon32x32 = "/favicon32x32.png"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Jonathan Davies"
  icon = "/apple-touch-icon.png"
  iconWidth = 35
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "Jonathan Davies"
  subtitle = "Get in touch"
  imageUrl = "https://media.licdn.com/dms/image/D4D03AQGAI8d3cVscrg/profile-displayphoto-shrink_400_400/0/1698154761548?e=1705536000&v=beta&t=zaN2q_QojalRO_QrRGnA9LlJAQvhSP-9dzuX3W5LRPs"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "Jonathan Davies"

  [params.homeInfoParams]
  Title = "Hi there 🤙"
  Content = "Welcome to my Digital Garden where I store notes related to SEO, Digital Marketing and Web3. Building this website is also a project, so if something is broken or looks weird, it probably means I'm still learning..."

  [[params.socialIcons]]
  name = "Linkedin"
  url = "https://www.linkedin.com/in/jtndvs/"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/jtndvs"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:jtndvs@gmail.com"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]